#include <iostream>
#include <filesystem>
#include <fstream>
#include <string>
#include <cstdlib>

using namespace std;
namespace fs = filesystem;

int main()
{
	// -----ZAD 1-----
	// WYKORZYSTAJ NASTĘPUJĄCE METODY: current_path(), append() ORAZ OPERATOR /()
	// UTWÓRZ OBIEKT TYPU PATH (I GO WYPISZ), KTÓRY PROWADZI DO PLIKU gratulacje.txt
	// A NASTĘPNIE WYPISZ JEGO ZAWARTOŚĆ 
	// (PROPONOWANA METODA: użycie obiektu ifstream oraz metody getline() z biblioteki <string>)
	// JEŚLI ZROBISZ ZADANIE POPRAWNIE OTRZYMASZ POCHWAŁĘ
	


	//TUTAJ ROZWIĄZANIE



	// -----ZAD 2-----
	// WYKORZYSTAJ METODY SKŁADOWE DEKOMPOZYCJI ŚCIEŻKI I WYPISZ:
	// ROOT-NAME, RELATIVE-PATH oraz FILENAME pliku szansaNaSukces.txt
	// WYPISZ TAKZE ROZSZERZENIE PLIKU przykladowyExcel



	//TUTAJ ROZWIĄZANIE



	// -----ZAD 3-----
	// WYŚWIETL ŚCIEŻKI DO WSZYSTKICH PLIKÓW z KatalogGlowny
	// WYKORZYSTAJ W TYM CELU ITERATORY
	// PRZYDATNA MOŻE SIĘ OKAZAĆ FUNKCJA path()

	try
	{
		//TUTAJ ROZWIĄZANIE


	}
	catch (fs::filesystem_error e)
	{
		cerr << e.what() << endl;
	}


	// -----ZAD 4-----
	// UWAGA!!! PO KAŻDYM WYKONANIU PROGRAMU USUŃ STWORZONE FOLDERY ORAZ PLIKI (inaczej wystąpią błędy)
	// UTWÓRZ KATALOG O NAZWIE Szef, W NIM KATALOG PodSzef, A W NIM KATALOG Pracownik
	// NASTĘPNIE UTWÓRZ TAM PLIK TEKSTOWY O DOWOLNEJ NAZWIE I ZAWARTOŚCI (NIE MOŻE BYĆ PUSTY)
	// SKOPIUJ PLIK TEKSTOWY, KTÓRY UTWORZYŁEŚ, A NASTĘPNIE FOLDER PodSzef BEZ ZAWARTOŚCI I NAZWIJ GO PodSzef2
	// SKOPIUJ Z ZAWARTOŚCIĄ FOLDER Szef I NAZWIJ GO Szef2
	// ZMIEN NAZWĘ JEDNEGO Z PLIKÓW STWORZONYCH PRZEZ CIEBIE
	// WYŚWIETL STRUKTURĘ PLIKÓW (ODKOMENTUJ ODPOWIEDNIĄ FUNKCJĘ, KTÓRA TO ZROBI)
	// SPRAWDŹ CZY ISTNIEJE FOLDER Szef2
	// POD KONIEC USUŃ FOLDER Szef2 (SPRAWDŹ RĘCZNIE CZY ZOSTAŁ USUNIĘTY PO WYKONANIU PROGRAMU)



	//TUTAJ ROZWIĄZANIE



}